### PR TITLE
fix(python): Include bridge modules in module reachability analysis

### LINKED ISSUE #92: Include bridge modules in module reachability analysis
Currently, if a module A depends on B and C **and** is set as `auto_install`, it is technically reachable from B or C but not currently detected by odoo-lsp.

### PR DESCRIPTION
**Pull request by gbrito**
closes #92

### CODE REVIEW

File: src/index.rs [hunk 1]
```diff
@@ -199,6 +203,37 @@ impl Index {
...
 	}
+	/// Find all auto_install modules whose dependencies are satisfied by the given set of modules
+	fn find_auto_install_modules(&self, loaded_modules: &HashSet<ModuleName>) -> Vec<ModuleName> {
+		let mut auto_install_modules = Vec::new();
+
+		for root in self.roots.iter() {
+			for (&module_key, module_entry) in root.iter() {
+				if module_entry.auto_install && !loaded_modules.contains(&module_key) {
+					// Check if all dependencies are satisfied
+					let all_deps_satisfied = module_entry.dependencies.iter().all(|dep| loaded_modules.contains(dep));
```
Comment (Desdaemon) [inline src/index.rs:214]: This is logically correct, but inhibits completions and gotodefs if not all modules are defined in dependencies list. Any suggestions for improving UX here?

File: src/index.rs [hunk 2]
```diff
@@ -199,6 +203,37 @@ impl Index {
...
+
+					if all_deps_satisfied {
+						debug!(
+							"Module {} is auto_install and all dependencies are satisfied",
+							_R(module_key)
+						);
+						auto_install_modules.push(module_key);
+					} else if module_entry.auto_install {
+						debug!(
+							"Module {} is auto_install but dependencies not satisfied. Deps: {:?}, Loaded: {:?}",
```
Comment (Desdaemon) [inline src/index.rs:224]: This could be promoted to a warning diagnostic if the user attempts to use an item that belongs to such a module

File: src/python/diagnostics.rs [hunk 3]
```diff
@@ -343,14 +355,53 @@ impl Backend {
...
+				} else {
+					// Multiple missing deps, just list them
+					missing_deps_with_chains
+						.iter()
+						.map(|(dep, _)| format!("'{}'", _R(*dep)))
+						.collect::<Vec<_>>()
+						.join(", ")
+				};
+				format!(
+					"Model `{}` has no property `{}`. This might be because module '{}' is marked as auto_install but cannot be loaded due to missing dependencies: {}",
```
[the remark this answers is not in the document]
Comment (gbrito) [reply src/python/diagnostics.rs:391]: Don't know if this is working properly, i dont see any errors at least

[the remark this answers is not in the document]
Comment (Desdaemon) [reply src/python/diagnostics.rs:391]: Looks fine in VSCode, unknown if support in other editors is up to par 
image

**Review by Desdaemon — APPROVED** [review]
Ready for merge, I would change the message to be this on my own time but you can do it too if you are free:

```
Model `foo` has no property `bar`
-> This property is defined in `sale_crm` (points to definition)
-> This module does not depend directly on `sale_crm`, or is missing one of `sale_crm`'s reverse dependencies (points to `sale`'s manifest)
-> `sale_crm` is defined as a bridge module here, alongside its reverse dependencies (points to `sale_crm`'s manifest)
```

**Comment by gbrito** [comment]
@Desdaemon Was getting some errors on the windows build related to the path. The error is now gone, can you evaluate the last commit. no idea if there is a better way to do this

File: src/python.rs [hunk 4]
```diff
@@ -556,12 +557,14 @@ impl Backend {
 		rope: RopeSlice<'_>,
 	) -> anyhow::Result<Option<Location>> {
 		let uri = &params.text_document_position_params.text_document.uri;
+		let file_path = uri.to_file_path().unwrap();
+		let file_path_str = file_path.to_str().unwrap();
 		let ast = self
 			.ast_map
-			.get(uri.path().as_str())
-			.ok_or_else(|| errloc!("Did not build AST for {}", uri.path().as_str()))?;
+			.get(file_path_str)
```
Comment (Desdaemon) [inline src/python.rs:564]: Check that you are consistent in which key is being used for ast_map

**Review by Desdaemon — CHANGES_REQUESTED** [review]
